# ─── labels.py ─────────────────────────────────────────────
# All 43 German Traffic Sign categories

LABELS = {
    0:  "Speed limit 20 kmph",
    1:  "Speed limit 30 kmph",
    2:  "Speed limit 50 kmph",
    3:  "Speed limit 60 kmph",
    4:  "Speed limit 70 kmph",
    5:  "Speed limit 80 kmph",
    6:  "End of speed limit 80 kmph",
    7:  "Speed limit 100 kmph",
    8:  "Speed limit 120 kmph",
    9:  "No passing",
    10: "No passing for vehicles over 3.5 tons",
    11: "Right of way at intersection",
    12: "Priority road",
    13: "Yield",
    14: "Stop",
    15: "No vehicles",
    16: "Vehicles over 3.5 tons prohibited",
    17: "No entry",
    18: "General caution",
    19: "Dangerous curve left",
    20: "Dangerous curve right",
    21: "Double curve",
    22: "Bumpy road",
    23: "Slippery road",
    24: "Road narrows on the right",
    25: "Road work",
    26: "Traffic signals",
    27: "Pedestrians",
    28: "Children crossing",
    29: "Bicycles crossing",
    30: "Beware of ice and snow",
    31: "Wild animals crossing",
    32: "End speed and passing limits",
    33: "Turn right ahead",
    34: "Turn left ahead",
    35: "Ahead only",
    36: "Go straight or right",
    37: "Go straight or left",
    38: "Keep right",
    39: "Keep left",
    40: "Roundabout mandatory",
    41: "End of no passing",
    42: "End no passing for vehicles over 3.5 tons"
}
